instrumentation:
   compact: false
   excludes:
      - doc/**
      - coverage/**
      - examples/**
      - node_modules/**
   include-all-sources: true
reporting:
   print: detail
   reports:
      - lcovonly
   watermarks:
      branches: [90, 100]
      functions: [90, 100]
      lines: [90, 100]
      statements: [90, 100]
check:
   global:
      branches: 100
      functions: 100
      lines: 100
      statements: 100
   each:
      branches: 100
      functions: 100
      lines: 100
      statements: 100
